networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.211.1.0/24

version: '3'   
services:
  web:
    image: docker.io/noabt/myapp:final
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      my_custom_network:
        ipv4_address: 172.211.1.2
    depends_on:
      - database
         
    environment:
       HOST: '172.211.1.3'  
       DB_USER: 'root'
       PASSWORD: 'noabt2410'
       PORT: '3306'
       MYSQL_ROOT_PASSWORD: 'noabt2410'

  database:
    build: 
      context: ./DB
    networks:
      my_custom_network:
        ipv4_address: 172.211.1.3
        
    environment:
      - MYSQL_ROOT_PASSWORD=noabt2410