{{- if .Values.app.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "myapp.serviceAccountName" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
  {{- with .Values.app.serviceAccount.annotations }}
  annotations:
    eks.amazonaws.com/role-arn: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
