name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'website/**'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git tag -l --sort=-v:refname | head -n 1)
        if [ -z "$latest_tag" ]; then
          latest_tag="v0.0"
        fi
        echo ::set-output name=TAG::$(echo "$latest_tag" | awk -F. -v OFS=. '{$NF=$NF+1;}1')
      
    - name: Build and Push Docker Image
      run: |
        docker build -t noabt/myapp:${{ steps.get_latest_tag.outputs.TAG }} .
        docker push noabt/myapp:${{ steps.get_latest_tag.outputs.TAG }}


