name: CD Pipeline 
on:
  workflow_dispatch:
  #push:
  #branches:
  #- main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        
    - name: Configure kubectl
      # can use also var or secret so it will be easy to change
      run: aws eks --region us-east-1 update-kubeconfig --name dsm-dev-eks

    - name: Install Argo CD CLI
      run: |
        curl -LO https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        sudo mv argocd-linux-amd64 /usr/local/bin/argocd

    - name: Argo CD Application Sync
      run: |
        kubectl config set-context --current --namespace=argocd
        kubectl apply -f argo-cd/application.yaml
        # can add monitoring applictions...
        argocd app sync dsm --wait

   
        

