name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install Flask-Testing
          pip install -r requirements.txt
            
      - name: Run Tests
        run: |
          pytest tests/
        
      - name: Get Commit SHA
        id: commit_sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          COMMIT_SHORT_SHA=$(git rev-parse --short=7 HEAD)
          docker build -t noabt/myapp:${BRANCH_NAME}-${COMMIT_SHORT_SHA} .
          docker push noabt/myapp:${BRANCH_NAME}-${COMMIT_SHORT_SHA}

      - name: Update values.yaml
        run: |
          export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          export COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)
          yq eval '.app.image.tag = env(BRANCH_NAME) + "-" + env(COMMIT_SHORT_SHA)' -i myapp/values.yaml

      - name: set git config
        run: |
          git config --global user.email "noabt123@gmail.com"
          git config --global user.name "noa"
        
      - name: stage changed files
        run: git add .
        
      - name: commit changed files
        run: git commit -m "Auto updating values.yaml"
        
      - name: fetch from master
        run: git pull origin main
        
      - name: push code to master
        run: git push origin HEAD:main


