name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: Get Commit SHA
        id: commit_sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Run Local Test
        run: |
          # Run Docker Compose locally
          docker-compose up -d

          # Wait for a moment to let containers start
          sleep 20

          # Run Docker Compose locally
          docker-compose up -d

          # Wait for a moment to let containers start
          sleep 15

          # Test if the app is running by making a request to localhost:3000
          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:3000)

          # Exit if response code is not 302
          if [ $response_code -ne 302 ]; then
            echo "Local test failed with response code: $response_code"
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          COMMIT_SHORT_SHA=$(git rev-parse --short=7 HEAD)
          docker build -t noabt/myapp:${BRANCH_NAME}-${COMMIT_SHORT_SHA} .
          docker push noabt/myapp:${BRANCH_NAME}-${COMMIT_SHORT_SHA}

