name: CI test

on:
  workflow_dispatch:
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install Flask-Testing
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest tests/

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
            BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
            COMMIT_SHORT_SHA=$(git rev-parse --short=7 HEAD)
            DOCKER_TAG=${BRANCH_NAME}-${COMMIT_SHORT_SHA}
            docker build -t noabt/myapp:${DOCKER_TAG} .
            docker push noabt/myapp:${DOCKER_TAG}
      
      - name: Update values.yaml
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          COMMIT_SHORT_SHA=$(git rev-parse --short=7 HEAD)
          yq eval '.app.image.tag=${BRANCH_NAME}-${COMMIT_SHORT_SHA}' -i myapp/values.yaml

      - name: set git config
        run: |
          git config --global user.email "noabt123@gmail.com"
          git config --global user.name "noa"
        
      - name: stage changed files
        run: git add .
        
      - name: commit changed files
        run: git commit -m "Auto updating values.yaml"
        
      - name: fetch from master
        run: git pull origin main
        
      - name: push code to master
        run: git push origin HEAD:main
        
