name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'website/**'

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install Flask-Testing
        pip install -r requirements.txt
            
    - name: Run Tests
      run: |
        pytest tests/

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t noabt/myapp:v.${{ github.run_number }} .
        docker push noabt/myapp:v.${{ github.run_number }}
