name: Docker Test, Build and Push

on:
  push:
    paths:
      - 'Dockerfile'
      - 'website/**'
      - 'tests/**'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        pytest tests/ || exit 1

    - name: Build and Push Docker Image
      run: |
        docker build -t noabt/myapp:${{ github.sha }} .
        docker push noabt/myapp:${{ github.sha }}
