name: Docker-compose test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t myapp-image:latest .

      - name: Update values.yaml
        run: yq eval '.services.web.image = "myapp-image:latest"' -i docker-compose.yaml

      - name: set git config
        run: |
          git config --global user.email "noabt123@gmail.com"
          git config --global user.name "noa"
        
      - name: stage changed files
        run: |
          git add .
          git commit -m "Auto updating docker-compose.yaml"
          git pull origin main
          git push origin HEAD:main
          
      - name: Run docker-compose
        run: docker-compose up -d
          
      - name: Wait for mysql Container to Start
        run: sleep 20
        
      - name: Run docker-compose
        run: docker-compose up -d

      - name: Wait for app Container to Start
        run: sleep 20

      - name: Check Response Code
        run: |
          APP_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
          if [ "$APP_RESPONSE" -eq 302 ]; then
            echo "App is running and returning a 302 response code."
          else
            echo "Connection to the app failed. Response code: $APP_RESPONSE"
            exit 1
          fi
