name: Docker-compose test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t myapp-image:latest .
        
      - name: Run MySQL Container
        run: |
          docker-compose build --build-arg CUSTOM_IMAGE_NAME=myapp-image:latest
          CUSTOM_IMAGE_NAME=myapp-image:latest docker-compose up -d
          
      - name: Wait for mysql Container to Start
        run: sleep 20
        
      - name: Run docker-compose
        run: |
          docker-compose build --build-arg CUSTOM_IMAGE_NAME=myapp-image:latest
          CUSTOM_IMAGE_NAME=myapp-image:latest docker-compose up -d

      - name: Wait for app Container to Start
        run: sleep 20

      - name: Check Response Code
        run: |
          APP_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
          if [ "$APP_RESPONSE" -eq 302 ]; then
            echo "App is running and returning a 302 response code."
          else
            echo "Connection to the app failed. Response code: $APP_RESPONSE"
            exit 1
          fi
